from abc import ABC, abstractmethod
from typing import Optional, List
from .entity import Product


class IProductRepository(ABC):
    @abstractmethod
    def get(self, id: int) -> Optional[Product]: ...
    @abstractmethod
    def list(self) -> List[Product]: ...
    @abstractmethod
    def find_low_stock(self) -> List[Product]: ...
    @abstractmethod
    def find_by_code(self, code: str) -> Optional[Product]: ...
    @abstractmethod
    def recent(self, limit: int = 50) -> List[Product]: ...
    @abstractmethod
    def search(self, q: str, limit: int = 30) -> List[Product]: ...
    @abstractmethod
    def save(self, product: Product) -> Product: ...
    @abstractmethod
    def add_movement(self, product_id: int, movement_type: str, quantity: int, reason: str) -> None: ...
