from abc import ABC, abstractmethod
from typing import Optional, List
from .entity import MaintenanceOrder


class IMaintenanceRepository(ABC):
    @abstractmethod
    def get(self, id: int) -> Optional[MaintenanceOrder]: ...
    @abstractmethod
    def list(self, status: Optional[str] = None, q: Optional[str] = None) -> List[MaintenanceOrder]: ...
    @abstractmethod
    def save(self, order: MaintenanceOrder) -> MaintenanceOrder: ...
    @abstractmethod
    def add_payment(self, maintenance_id: int, amount: float, payment_date, memo: Optional[str]) -> dict: ...
    @abstractmethod
    def add_part(self, maintenance_id: int, part_name: str, quantity: int, unit_price: float,
                 product_id: Optional[int] = None) -> dict: ...
    @abstractmethod
    def delete_part(self, part_id: int) -> None: ...
    @abstractmethod
    def find_by_estimate_id(self, estimate_id: int) -> Optional[MaintenanceOrder]: ...
    @abstractmethod
    def replace_parts(self, maintenance_id: int, parts: List[dict]) -> None: ...
    @abstractmethod
    def delete_payments(self, maintenance_id: int) -> None: ...
    @abstractmethod
    def add_photo(self, maintenance_id: int, content_type: str, image_data: bytes) -> dict: ...
    @abstractmethod
    def delete_photo(self, photo_id: int) -> None: ...
    @abstractmethod
    def get_photo(self, photo_id: int) -> Optional[tuple]: ...
