from abc import ABC, abstractmethod
from typing import Optional, List
from .entity import Equipment


class IEquipmentRepository(ABC):
    @abstractmethod
    def get(self, id: int) -> Optional[Equipment]: ...
    @abstractmethod
    def list(self) -> List[Equipment]: ...
    @abstractmethod
    def find_by_chassis(self, chassis_number: str) -> List[Equipment]: ...
    @abstractmethod
    def find_by_customer(self, customer_id: int) -> List[Equipment]: ...
    @abstractmethod
    def save(self, eq: Equipment) -> Equipment: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...
